default:
  bucket: cumulus-test-sandbox-internal
  apiUsername: jasmine
  pdrNodeNameProviderBucket: cumulus-sandbox-pdr-node-name-provider

cumulus-sit:
  bucket: cumulus-sit-internal
  apiUsername: jasmine
  pdrNodeNameProviderBucket: cumulus-sit-pdr-node-name-provider

mboyd-int-tf:
  bucket: mboyd-int-tf-internal

mvd-tf:
  bucket: mvd-internal

mvd-dev-tf:
  bucket: mvd-internal

jl-tf:
  bucket: jl-test-integration-internal

kk2-tf:
  bucket: kk2-tf-internal

lf-test-tf:
  bucket: lf-internal

mth-ci-tf:
  bucket: mth-internal

mth-dev-tf:
  bucket: mth-internal

lpf-tf:
  bucket: lf-internal

lpf:
  bucket: lf-internal

mhs3:
  bucket: mhs3-internal

mhs2:
  bucket: mhs2-internal

bt-tf:
  bucket: bt-internal

jtran-int-tf:
  bucket: jtran-int-tf-internal

jtran-tf:
  bucket: jtran-internal

np:
  bucket: npauzenga-internal
